config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :charity_datas
  root 'charity_datas#index'

end

app/models/charity_contribution.rb
class CharityContribution < ActiveRecord::Base
	belongs_to :charity_data
end

app/models/charity_data.rb
class CharityData < ActiveRecord::Base
	has_many :charity_contributions
	has_many :charity_expenses

	def self.search(search)
	  if search
	  	@charity_data = CharityData.where("charity_name LIKE '%#{search}%'")
	  else
	  	@charity_data = CharityData.all
	  end
	end
end

app/models/charity_expense.rb
class CharityExpense < ActiveRecord::Base
  belongs_to :charity_data
end

app/models/charity_expenses.rb
class CharityExpense < ActiveRecord::Base
  belongs_to :charity_data
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/charity_datas_controller.rb
class CharityDatasController < ApplicationController

	def index
	  @charity_data = CharityData.search(params[:search])
	end

	def show
	  @charity_data = CharityData.find(params[:id])
	  @charity_expenses = @charity_data.charity_expenses

		respond_to do |format|
		format.html
	  	format.json { render :json => @charity_expenses }
	  
  end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/charity_datas/index.html.erb
<div class="wrapper">
  <div class="grid-container">
      <div class="row">
          <div class="col-1"><img src="http://s28.postimg.org/5kmgufhel/pual_miller_logo.png" class="logo"/></div> 
          <div class="col-4-B">
            <p>Search Your Favorite Charity</p>
              <%= form_tag charity_datas_path, method: 'get' do %>
                <p>
                  <%= text_field_tag :search, params[:search], :class => "search"%>
                <% end %>
                </p>
          </div> 
          <div class="col-1">
            <!-- <div class="nav-icon">

              <label for="menu-toggle">   

                <input type="checkbox" id="menu_opener_id" class="menu_opener">

                  <label for="menu_opener_id" class="menu_opener_label">
                    
                  <div class="barre_hamburger"></div>

                  </label>

                </input> 
              </label>  -->
            </div>  
          </div> 
      </div> 
      <div class="row">
          <div class="col-6-B">
            <h2>What Is Charity Informer?</h2>
              <p class="expando">Donating to charities 
                <expando>
                  <initial><a>is awesome.</a></initial>
                  <expanded>
                    has been a long-standing tradition of awesome people everywhere, whom decide to spend their hard earned money not on gadgets, but on the betterment of humanity both domestic and abroad.
                  </expanded>
                </expando>
                    But there are
                <expando>
                  <initial><a> bad, greedy people in this world.</a></initial>
                  <expanded>business-savvy individuals who decide to capitalize on this notion, setting up faux-charities, which by design never live up to their promises. 
                  </expanded>
                </expando>
                    Fortunately, things aren't
                <expando>
                  <initial><a>hopeless.</a></initial>
                  <expanded>hopeless, with services like <a href="http://www.charitynavigator.org/" class="charitynav">Charity Navigator</a> pouring over the tax records of all organizations that identify themselves as philanthropic in nature and publish their findings, with the intention of exposing such fraudulent practices. 
                  </expanded>
                  However, even with today's technology, it's still quite difficult to come to an informed decision on the fly.</p>
              <p> I'm here to fix that.</p>
          </div> 
      </div> 
      <div class="row">
        <div class="col-6">
          <div id="owl-charities" class="owl-carousel">    
            <% @charity_data.shuffle.each do |charity_data| %>
              <div class="charity_links">
                <div class="charity_images">
                  <a href="charity_datas/<%=charity_data.id%>">
                    <img src="<%= charity_data.charity_logo %>"/>
                    </a>
                  </div>
                </div>
              <% end %>
            </div>
        </div> 
      </div>
<!--       <div class="row">
          <div class="col-3"><p>Highchart.js</p></div>
          <div class="col-3"><p>Charity Info</p></div> 
      </div> -->
  </div>
  <div class="push"></div>
</div>

<div class="footer">
  <p>Site designed by Paul Miller</p>
</div>

app/views/charity_datas/show.html.erb
<div class="grid-container">
	<div class="row">
	  <div class="col-3">
	  	<div id="container" style="min-width: 310px; height: 400px; max-width: 600px; margin: 0 auto"></div>
	  </div>
	  <div class="col-3" id="description">
		  <p>
		  	<%= @charity_data.charity_desc %>
	  	</p>
		  <p>
	  		Tonx wolf bitters art party. Meh slow-carb Blue Bottle try-hard distillery, flexitarian Thundercats umami letterpress Portland craft beer Austin you probably haven't heard of them. Locavore slow-carb DIY you probably haven't heard of them mumblecore cred. Meditation distillery food truck, shabby chic deep v master cleanse Marfa biodiesel synth gluten-free semiotics fap flexitarian next level sartorial. Cred 3 wolf moon seitan tote bag. Bushwick aesthetic shabby chic slow-carb pop-up locavore, heirloom crucifix kogi deep v wolf bespoke craft beer Austin chillwave. Raw denim messenger bag street art bespoke Truffaut.
	  	</p>
	  	<p>
	  		Single-origin coffee Brooklyn ennui Odd Future banjo. Yr PBR single-origin coffee, hella cornhole distillery blog cold-pressed normcore. Umami shabby chic retro, Tumblr American Apparel art party tousled pork belly direct trade. Sriracha narwhal asymmetrical, tattooed skateboard Marfa mlkshk bitters letterpress. Chambray Pitchfork pop-up High Life. Locavore yr Etsy sustainable mumblecore, plaid DIY street art taxidermy master cleanse. American Apparel keytar cardigan Williamsburg fixie ennui.
	  	</p>
	  </div> 
	</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CharityInformer</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>